### ISSUE TITLE
[Feature] tokenizer playground update

### ISSUE THREAD

**Issue by huyiwen** [lenML/tokenizers#2]
Is there any chance that the [tokenizer playground](https://lenml.github.io/llama-tokenizer-playground/) could be updated to support selecting different models? This enhancement would greatly increase its versatility and utility for users working with various model versions and configurations.

**Comment by zhzLuke96** [comment]
Hey there! I think there might be a bit of confusion. The playground you're looking at isn't actually for this library (`@lenml/tokenizers`).

The real demo is over here: https://lenml.github.io/tokenizers-arena/

This one's got all the tokenizers, and you can even load pre-built tokenizers from a URL (basically, tokenizers that have been turned into JSON files already).

Give it a try - I think it'll have what you're looking for!

**Comment by huyiwen** [comment]
This is exactly what I'm looking for! That's awesome! Thanks.
