### ISSUE TITLE
Update to transformers.js 2.17.2

### ISSUE THREAD

**Issue by zcbenz** [lenML/tokenizers#3]
It added support for sequence post processor (https://github.com/xenova/transformers.js/pull/771) which is required for using the tokenizer of llama3.1 .

**Comment by zhzLuke96** [comment]
added https://github.com/lenML/tokenizers/commit/a207e3d566e4c17d08325e76e40e9705b673c45a

and publish llama3.1 package [`@lenml/tokenizer-llama3_1`](https://www.npmjs.com/package/@lenml/tokenizer-llama3_1)
