### ISSUE TITLE
[Feature] Update to transformers.js@3

### ISSUE THREAD

**Issue by zcbenz** [lenML/tokenizers#5]
transformers.js v3 has been marked as latest and all bug fixes now only go to v3, and I would like to get bug fixes for issues like https://github.com/xenova/transformers.js/issues/879 and https://github.com/xenova/transformers.js/issues/959.

I wonder if you can update this module to use transformers.js@3?

**Comment by zhzLuke96** [comment]
Done https://github.com/lenML/tokenizers/commit/22d3fa2516dd5bbb3e9a68384db0c67f06689330
npm package: [@lenml/tokenizers@3.0.1](https://www.npmjs.com/package/@lenml/tokenizers/v/3.0.1)

It's worth noting that transformers.js is still in [3.0.0-alpha.3](https://github.com/xenova/transformers.js/commit/8891a142859782a6a4a622056741f1a5be55e93b), so there may be potential issues.

**Comment by zcbenz** [comment]
Thanks!
